### ISSUE TITLE
Error during project initialization

### ISSUE THREAD

**Issue by periwinkleFTW** [jolo-dev/zappa-template#1]
I get this error after I enter the bucket name:
```
Traceback (most recent call last):
  File "/var/folders/_p/0qlglv9s7hx4sxv_gkpjtspw0000gn/T/tmpt_vri07o.py", line 5, in <module>
    import boto3
ModuleNotFoundError: No module named 'boto3'
ERROR: Stopping generation because post_gen_project hook script didn't exit successfully
Hook script failed (exit status: 1)
```

Any idea what might be causing it?

**Comment by jolo-dev** [comment]
Hi @periwinkleFTW ,
Did you do
```bash
pip install --upgrade pip # In case you need to
pip install -r requirements.txt
```

**Comment by periwinkleFTW** [comment]
It fails during the project setup stage right after I enter the bucket name, there is not requirements file because the project has not initialized yet
```
Select engine:
1 - Flask
2 - Django
Choose from 1, 2 [1]: 2
aws_bucket_name [zappa-project-periwinkle]: zappa-template-bucket
Traceback (most recent call last):
  File "/var/folders/_p/0qlglv9s7hx4sxv_gkpjtspw0000gn/T/tmp8fhdf8nv.py", line 5, in <module>
    import boto3
ModuleNotFoundError: No module named 'boto3'
ERROR: Stopping generation because post_gen_project hook script didn't exit successfully
Hook script failed (exit status: 1)
```

I use MacOS Catalina, PyCharm, and the project is being initialized inside the venv.
I have no problem starting plain cookiecutter projects

**Comment by jolo-dev** [comment]
Oh you are right. 
I have the same issue. Let me investigate a bit further

**Comment by jolo-dev** [comment]
Hey @periwinkleFTW ,
I made a fix. Let me know if that works.

**Comment by periwinkleFTW** [comment]
I get this error during initialization:
```
Requirement already satisfied: six>=1.5 in ./.env/lib/python3.6/site-packages (from python-dateutil<3.0.0,>=2.1->botocore) (1.15.0)
WARNING: You are using pip version 20.2.3; however, version 21.0.1 is available.
You should consider upgrading via the '/Users/periwinkle/PycharmProjects/django-zappa-template/zappa_project/.env/bin/python -m pip install --upgrade pip' command.
/Library/Frameworks/Python.framework/Versions/3.6/Resources/Python.app/Contents/MacOS/Python: can't open file './create_bucket.py': [Errno 2] No such file or directory
```
Project structure seems to have been created, but not sure about this error

**Comment by jolo-dev** [comment]
Now I think I got it :)

**Comment by periwinkleFTW** [comment]
Now I get get this error:
```
 ERROR:root:An error occurred (InvalidLocationConstraint) when calling the CreateBucket operation: The specified location-constraint is not valid
```
Also I get the message that a bucket for static files was created but there is no new buckets when I check the console

**Comment by jolo-dev** [comment]
What is your region in your aws setup?
Mine is `eu-central-1`.
It could be that we have to check the region before creating a bucket: 
https://gaurabb.com/2016/09/30/aws-s3-error-invalidlocationconstraint-the-specified-location-constraint-is-not-valid/

**Comment by periwinkleFTW** [comment]
My region is ca-central-1. Aren't buckets global? Lambda requires a region though. Maybe there is a rogue region setting that messes up the initialization

**Comment by jolo-dev** [comment]
Can you change your local region to one in the us by 
`aws configure` in your terminal?
